name: PullRequest

on:
    pull_request_target:

permissions:
    contents: write
    pull-requests: write

jobs:
    Duster:
        name: Duster
        uses: EncoreDigitalGroup/.github/.github/workflows/dusterFixBlame.yml@v1
        permissions:
            contents: write
            pull-requests: write

    StaticAnalysis:
        needs: Duster
        name: StaticAnalysis
        uses: EncoreDigitalGroup/.github/.github/workflows/larastan.yml@v1
        with:
            branch: ${{ github.head_ref }}
            path: 'src/'
            phpVersion: '8.3'

    Test:
        needs: Duster
        name: Test
        uses: EncoreDigitalGroup/.github/.github/workflows/pest.yml@v1
        with:
            useLaravelEnvDecryptionKey: false
            useComposerAuthJson: false
            phpVersion: '8.3'
            branch: ${{ github.head_ref }}
            enforceCoverage: false

    AutoMerge:
        needs: [ StaticAnalysis, Test ]
        name: AutoMerge
        uses: EncoreDigitalGroup/.github/.github/workflows/dependabotAutoMerge.yml@v1